language: ruby
sudo: required
rvm:
- 2.3.1
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="lpsandaruwan/lpsandaruwan.github.io"
  - secure: QWxXKQpmVICz2yNPHjbZroYgQfbJEXR2F+fktj+mnwwZxflDBkoka8b9f+q5MvFWJm/B5V6HOUpZyUK+cHBmDqlbBCO5fyXNB5PV/NE2gmeWyUzwRiozsMQ7tYaXYaks/ISWMOaNN5mzShtgylaID9+gJu2Zfs9op3TM1VZu7wpVDgDgPpk4LEGP/AFE2qaLwZay+Jty41FegrD2aYUyYawFi/LkbVsLkKDnKq8DkcUrkM0b14ZtY4LSzXAK5xDOBPEsslPHcrf6c6HvAQqKEbFflOl2tKiG6f2Mvt32h4/eR6kmOQizitthebX0r0Z+dg2P6LRJ6O4tQQBY8RP5ebjA2veJG0TitG/dP9KZzx6SeeiAC5d9yN1l0DbY47RXejCI+7U22BHIoUyn9v+5KF03qjZVkIbPeRs3fgotTc90UyNqVq11LcrNJNWmok0gmCwK785PDY/3sKLFEJwdCTnB/kaSCHgwTZXNUc3hlV1MaP88gm7QFoOLkbkaHJNqex8RBhXGe6skhPxmb9pyAHMUCUI+NzpA7IzK/MBAblX57IzPt6SeNXokfGqGhspc1TNrMga6BMPha2phLmZaRit0bhOInsz1Nty7VJ1wqC9ox3KuILcwa5wNl6ecxIf7oqe6QXevBvD4XQ+4NNy1si/Cp1H8kYwti5MSq/vlMuo=
branches:
  only:
  - master
  - source
notifications:
  email: true
